### ISSUE TITLE
Should this documentation be published into the internet?

### ISSUE THREAD

**Issue by viniciusgama** [techops-platform/documentation#5]
Currently we are using GH pages to publish this docs, and it creates it under a github.io domain, which is  public. There is any risk on having this public?

I was imagining we would use this markdown to generate the content and publish it in a custom domain and protect it with OKTA.

Then plan is to stick with this solution moving forward or this is just a temporary solution?

**Comment by veller** [comment]
Bear in mind some of the content is based on DPS material. We are waiting for a formal approval from them to use their content although we won't stay blocked because of that.

**Comment by Stono** [comment]
Hey, 
The idea of this repo was to be external open source, to allow anyone to contribute.  That was actually the plan for all the techops-platform repos actually!  I think there's something quite nice about publishing our API style guidelines etc.  What exactly is it in this repo that we feel needs to be behind Okta, and only available to ThoughtWorkers?

The reason it was decided against on the more code related repositories for now was because maintaining open source software carries an overhead that we'd struggle to absorb.

**Comment by Stono** [comment]
Here is another example of ThoughtWorks written yet open source information: https://github.com/cairnsc/security-playbook

**Comment by veller** [comment]
We got to a conclusion during the stand up:
1. We'll keep using DPS content and add our own style and examples to the documentation along the way;
2. We'll make the documentation public to the interwebs regardless of item #1
3. On documentation, we'll use links to DPS content with a message that that's for ThoughtWorkers' access only (suggestion: *If you're a ThoughtWorker, read more about it on our DPS internal documentation here*)

**Comment by veller** [comment]
By the way, we just got Lucas' (DPS team) answer:

> ​Hi guys, 
> Sorry for not replaying earlier, we had our face to face this week and with the subsequent conversations, ended up missing this.
> We have no problems with techops using the material and providing appropriate reference. Go for it.
